language: python
root: required
compiler:
- gcc
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
addons:
  apt:
    packages:
      - cmake
env:
  global:
  - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
install:
- pip install -r tests/requirements.txt
- python setup.py install
script:
- python setup.py check -rms
- flake8
- pytest tests/
deploy:
  skip_cleanup: true
  distributions: 'sdist bdist_wheel'
  provider: pypi
  user: rasmunk
  password:
    secure: "ZQNLbdYd4US6WywLoPFMbpVJOeSQTYfF8/8Y8vXhAAZp4WiZGeHIiSXeEkmEGFvo5lCm4EKUHOEe0LhhbgbSrZ/kID8Bm3w9qxJ9err7cUPdJGvXi9P0gFPuK58B5uA3AH4u6ZXipS4lUwWeojtrLsufH5RBHa4AqqcLZE8BESSXkvO5xI/jUWDDHD31Ht94mNM/7NtWvWBhDmoZuH8xqrMzwDdBBuVczPaaITGwNXP1qS0Cpl5kBfCQqMzUlvGqRx4cCbFHR7Hahq0vIY2wN+nqIeSJLAeSrhuVATPK938XP7iErZhDUfhwFwn6IiGbYPoLeOVQ8oQ7R8fecazbK92rxNUPoSacY6Wve8Le+vOaHWnTgORcSowYsGa5Jbo5yDPgYKu6fVmAB4leGjNByRKj/vaSM7qDMLSzokkql2kdQd+kFJbi3LoZXGNU1fCr0PkXzefB8vjU8Q6QXZWxTKOWQcnWcnaxT5v0oVAsq8chWH7BKeE0X49eKR5XZLFG4eYVL/Hdjvb90TX5Fn+R4FqlzcDfb42fbDkdoUCb1svUY1MHGnEo2h+UcYJ6BZu1UBm0e/XkkkBVC5CCiXkC5KNCbU9dsfaUoO24ftdlSM6WZApY8tfODl4y3DY75/hqa7Lp6ty5cumpZD3BKbFF7qEiUr3kspK+cPXBiWZGA4E="
  on:
    tags: true
    branch: master
