language: python
sudo: required
compiler:
- gcc
python:
- '2.7'
- '3.5'
- '3.6'
- '3.6-dev'
addons:
  apt:
    packages:
      - cmake
env:
  global:
  - secure: kW4STd+IVlRyFko8Xa77vKsq+g2AelScC5vHUkGKWSoEy2TFTFXvGEDJeppJ2PLi9Xz4Tp68pl2S2SsyiBA9bm+5gn7Ejgg+PsyYY2jdX53kGO555geE10CW8zInPrhYWhQViJ+7uk8jxYFvK3oCO3MAqWQwhtb9dH7vJ3Z8V6AoVzE1fOtbdtoF9ZqDMLzft1Y5fPUpCoHZCtmveJQVPzmJQRHHwXkHgUYvBoiCplBGotax+EwUNszBEps1Nukpb0vsozBZlrG4OLl3kyGQuFGecmzX8lr2nmpLcMCPOs0ntVjsRZF77ciCiJTrNOP3HCVgV6e7jpm4pkurffhKMOLBw00mGQzDww899jRIHhpAHRwCFGkfMuBgLrvFu+y1i0E0wrsLOIAXgBQ2CBi+xS4CExGMAK+hIezcIGJdtMDybKDXetMgd8+8Tw2RCPY3S2Pw0S+TirJCc37wbNlyLIHHPNzifITw5lTBiQZNyNKDzc482KCeIG5hHADC5O8InOloaY6Yyirh5eAoBTrBYuYRnHqwugWEta46SbKM0cT9bexWhDUfsbj9AecwlkZY5YvK8+fCAqJc0NKjs1+9lpfPJJYAa+rAC9JhoG/vE7NSS17d8qEHPrvbsTbSUppGL3jz0H0M83W0yZQoUMAhxh14EzWv4zJa3+Y2kWB1Hlc=
  - secure: AHKBlInxtMqfw2tUufm87og8MhIRiWDDctLklXAcGO7Yd1E4eSkBYeWUY7wjphAo560hhAh+LCO0irPGVKOkpkWysThCOAgGatXZXdXU298pJQSYmgAbbifusHOqm26hYZo34QFKs4NTx0JjOwjY1hynFiqvMtys9jr/v29EWC6C0xcYm2jN+1rPsLi5v7t5BIRfJdxUhfXsOrl63D7BCuChXATWqkTCSusvbS8/y+95PaxsdZofmXoYvcoOuT/e30sewIgynYP7Mpv01l3u4ykH73yWKAGOYtvLVN0n3cZWbyHkZZ3r/l65e/0Cuu2nBMw8RpFukQ2iGzK+Fs90yo/4yBnOttupiSUdWt6uciagFMsqdapfjyGdWuI0cGA+NI2s8oC2A9F7/zH/Qdnnp+H4cFOQZSggH6HQtS1PelfRzv66cgJWDEhIkeMg7qyqXGnnHN/yBuVDFPH9FKGdJxRvl58133TxAMTCpjODq9T+uQXiXwJxPTvqhZM7wTTrDB2Os0NaRpqPSnhvCv+IQ3p8E4NQXJy18Ki6iG2cTpI7CDT72y623DPQoAtzdNt3bMMIaHjF49VMgHdsa2AFQRkMjo1wNtV+DVrykKRdIYQWwf/SFrLuvjt/rxNfDDygqzrGFp9YxnEUo1WV8txbgDaFqG48HSMNrwlO2+2vk/o=
  - LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu
install:
- pip install -r tests/requirements.txt
- python setup.py install
script:
- python setup.py check -rms
- flake8
- pytest tests/
deploy:
  skip_cleanup: true
  distributions: 'sdist bdist_wheel'
  provider: pypi
  user: rasmunk
  password:
    secure: "ZQNLbdYd4US6WywLoPFMbpVJOeSQTYfF8/8Y8vXhAAZp4WiZGeHIiSXeEkmEGFvo5lCm4EKUHOEe0LhhbgbSrZ/kID8Bm3w9qxJ9err7cUPdJGvXi9P0gFPuK58B5uA3AH4u6ZXipS4lUwWeojtrLsufH5RBHa4AqqcLZE8BESSXkvO5xI/jUWDDHD31Ht94mNM/7NtWvWBhDmoZuH8xqrMzwDdBBuVczPaaITGwNXP1qS0Cpl5kBfCQqMzUlvGqRx4cCbFHR7Hahq0vIY2wN+nqIeSJLAeSrhuVATPK938XP7iErZhDUfhwFwn6IiGbYPoLeOVQ8oQ7R8fecazbK92rxNUPoSacY6Wve8Le+vOaHWnTgORcSowYsGa5Jbo5yDPgYKu6fVmAB4leGjNByRKj/vaSM7qDMLSzokkql2kdQd+kFJbi3LoZXGNU1fCr0PkXzefB8vjU8Q6QXZWxTKOWQcnWcnaxT5v0oVAsq8chWH7BKeE0X49eKR5XZLFG4eYVL/Hdjvb90TX5Fn+R4FqlzcDfb42fbDkdoUCb1svUY1MHGnEo2h+UcYJ6BZu1UBm0e/XkkkBVC5CCiXkC5KNCbU9dsfaUoO24ftdlSM6WZApY8tfODl4y3DY75/hqa7Lp6ty5cumpZD3BKbFF7qEiUr3kspK+cPXBiWZGA4E="
  on:
    tags: true
    branch: master
    python: '3.6'
notifications: 
  slack: raz-s:se1PurXsQJv03nBZa9XWMOOS
