language: python
python:
- '2.7'
- '3.6'
- '3.6-dev'
env:
  global:
  - secure: Ipty3wr7N1qALYLqbK464qrpv9o3Y0dgHJCAKKKGDCfLRi3k7dd6Gh903H7NPst8lp5GMqrHZ/B4mUGdRqQUYdpk/NuL8N/u3SzyuQkW+l4RftAJxrEaJ7tfPOoeS8uQBR4TJeQjR3Aaj6/x1qfX+ungUZ19u+Pyvo2avEX66zrw5APC58JkmRVx7j/v+RftdQ+3b/uA73omwN4Qr97sxOjzbp8heVOopcKyKUdHfGSvbIWp89V9ud5mRtGY9bfW9COfa6iwubwYWQpmeQN6zPiJ4olngCK9erBb5KHezNGRPRxPUMFJQ4ij7/z21iFrpN5cWVzhsrTLOpiiN49BTl/OQaMR5eTJXfWKpuyqg51ZmgyD9k4gJBCCyp3arx7JID2CXYzOJmBg+ybbsx2KILj49z218tiTKyzMDMh3lEervq+mMZDWXjXlFJrfVczHIGmGuiRpqXQhEFRETWznzSZttbeSz+EpRwnYnwnfC/LxYA4N25R73eeWwcaysM7+q74ekHwoUntr8uxfYl/o33LLRSgJfYy3t+1KQw1sx9he5b7SaTV+xWMXgqMqKvs9MEnzL+v0/09dxAq9SAS1suf8On849hiG/pLko5a2rPiWuBigE3Ki3EC6WOXxn0wJy2n2FP6eqBWuf65kBs3wEHWNpdfn9wW+N13jrXDp+JE=
  - secure: jA6TL+HikfDcsEuZDkcHTUTwhe5tNjR2UUhiE8Ff+ofCL7/1q/eSKaHK+gauhdvRYPo/sssGxe3+22UZUzXy/o7RLKin6x4QNsMKKldSqi9v103MY4IGpt7bA6SSL0ycwyPtA4bhjds2WM19kb+JmJQ0Ih5gJkZWaGzPVSAAyNTen84XP08xqoXHu5mmze4fRy6iBZ4DSG0Mw9hBPpFepQWQJWxNtAQXb5qpunW11rmF9sexxIserEjYEOhI19On704bc7cLhL3rkjcZcFEXXZDiochBcAlJC4c1zVKCNnUXKx32ToPcPw1LeMGDIwhBI9FSC3l2OPlGNoCW6Z4JRr+Llp8J3T1vZwy/kWoNQ9rhifDPzW8khI6UnQFqEp59abUVzgFPikvKxkHP0MyNpaXxygyzy2MTqCavs2aHMV1RDP0KFrahw57TWGYzKUlk1LFbcYnn4WHcvTp2nmrmHIZyJFEc3JAQ0rzbRhkCtG/5yPN5fLCfqm7Ak450VhYVHpuiv03SlBuvidgR3ZqGSfaRgG+THRmxK26/9zD3hDPlPpdnyP/3/KN5GVap2pjpM9yfpcae5vBW3snmx/k8gibfpYZ/SyyXTBBD259sAmqJHsbyteM42R12k6RhAP1j0tYaoPT5gD2YozlRN8pDn+EljmRtMEHfpuK1/eJLYio=
install:
- pip install -r tests/requirements.txt
- pip install -r requirements.txt
- python setup.py install
script: pytest
deploy:
  skip_cleanup: true
  distributions: 'sdist bdist_wheel'
  provider: pypi
  user: rasmunk
  password:
    secure: "ZQNLbdYd4US6WywLoPFMbpVJOeSQTYfF8/8Y8vXhAAZp4WiZGeHIiSXeEkmEGFvo5lCm4EKUHOEe0LhhbgbSrZ/kID8Bm3w9qxJ9err7cUPdJGvXi9P0gFPuK58B5uA3AH4u6ZXipS4lUwWeojtrLsufH5RBHa4AqqcLZE8BESSXkvO5xI/jUWDDHD31Ht94mNM/7NtWvWBhDmoZuH8xqrMzwDdBBuVczPaaITGwNXP1qS0Cpl5kBfCQqMzUlvGqRx4cCbFHR7Hahq0vIY2wN+nqIeSJLAeSrhuVATPK938XP7iErZhDUfhwFwn6IiGbYPoLeOVQ8oQ7R8fecazbK92rxNUPoSacY6Wve8Le+vOaHWnTgORcSowYsGa5Jbo5yDPgYKu6fVmAB4leGjNByRKj/vaSM7qDMLSzokkql2kdQd+kFJbi3LoZXGNU1fCr0PkXzefB8vjU8Q6QXZWxTKOWQcnWcnaxT5v0oVAsq8chWH7BKeE0X49eKR5XZLFG4eYVL/Hdjvb90TX5Fn+R4FqlzcDfb42fbDkdoUCb1svUY1MHGnEo2h+UcYJ6BZu1UBm0e/XkkkBVC5CCiXkC5KNCbU9dsfaUoO24ftdlSM6WZApY8tfODl4y3DY75/hqa7Lp6ty5cumpZD3BKbFF7qEiUr3kspK+cPXBiWZGA4E="
  on:
    tags: true
    branch: master
    python: '3.6'