language: python
python:
  - '2.7'
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
install:
  - pip install -r tests/requirements.txt
  - pip install -r requirements.txt
  - python setup.py install
script:
  pytest