environments:
  bare_metal_pypi_package:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      ERDA_TEST_SHARE: "{{SECRET:[deling][erda_test_share]}}"
      LD_LIBRARY_PATH: /usr/local/lib/x86_64-linux-gnu
    pipelines:
      - deling
pipelines:
  deling:
    group: pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      deling_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rasmunk/deling.git
        branch: master
        destination: deling
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: deling
      TEST_DIRECTORY: deling
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package
